### ISSUE TITLE
wrong organization

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/regular_dicers_bot#1]

**Comment by torbencarstens** [comment]
https://github.com/woog-life/regular_dicers_bot/blob/42c5d6ed0dae06276deaf714461d73af6fca8ba6/templates/update_handler.yaml#L5 and namespace

**Comment by BjoernPetersen** [comment]
To be perfectly honest I just wanted to use the organization secrets 😅. You weren't available yesterday, I don't think I have access to the other namespaces, and I tried to get this shitpost of a project up and running before abandoning it for months.

**Comment by torbencarstens** [comment]
I've added a repository secret `KUBECONFIG` (base64 encoded) to OpenAlcoholics/regular_dicers_bot which contains a serviceaccount which has admin rights in the `stammgaeste` namespace.
